import type { Metadata } from "next";
import { Chakra_Petch } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const chakra = Chakra_Petch({
  variable: "--font-chakra",
  subsets: ["latin", "thai"], // 
  weight: ["400", "600", "700"], // ลดขนาด font bundle โดยเลือกเฉพาะที่จำเป็น
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${chakra.className} antialiased flex flex-col min-h-screen`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
